### ISSUE TITLE
Uncaught (in promise) SyntaxError: Unexpected non-whitespace character after JSON at position 4

### ISSUE THREAD

**Issue by zimmra** [SteamDeckHomebrew/decky-plugin-store#12]
Unable to load https://beta.deckbrew.xyz

Getting:
```
Uncaught (in promise) SyntaxError: Unexpected non-whitespace character after JSON at position 4
```

and

```
GET https://beta.deckbrew.xyz/plugins?query= 500
```

![image](https://user-images.githubusercontent.com/28514085/187049513-767e3da3-923f-4d15-bc32-c51d08ea07ce.png)

**Comment by TrainDoctor** [comment]
Apologies the store is down and we're moving to fix it. Unknown ETA. Check github actions for the latest version of all the plugins.

**Comment by TrainDoctor** [comment]
Alright server is restarted and in turn https://github.com/SteamDeckHomebrew/decky-loader/issues/156 and https://github.com/SteamDeckHomebrew/decky-loader/issues/157 (duplicates of this issue) should now be resolved.
