### ISSUE TITLE
Allow updating images for the store

### ISSUE THREAD

**Issue by Scrumplex** [SteamDeckHomebrew/decky-plugin-store#17]
The first release of vibrantDeck just used the logo of libvibrant as the preview image.
I have added a screenshot since then, but it seems like the release scripts here do not update that image for later releases.

So it would be nice if the release scripts would also update the image of a plugin for each release

**Comment by TrainDoctor** [comment]
> The first release of vibrantDeck just used the logo of libvibrant as the preview image. I have added a screenshot since then, but it seems like the release scripts here do not update that image for later releases.
> 
> So it would be nice if the release scripts would also update the image of a plugin for each release

It technically does update the image, it grabs the latest image and uploads it to the plugin-store, but because it currently uses URLs rather than image files, we're kind of stuck in our current situation. I'll look into this when I get the time.

**Comment by TrainDoctor** [comment]
I'm going to move this to the store repository as this is a feature that the store should support and the CI should check for updates to the images and then upload them.

**Comment by TrainDoctor** [comment]
@gbdlin is now working on store features that would provide this functionality.

**Comment by TrainDoctor** [comment]
We might return to this later, but this is going to have to go onto the backlog as we've grown busy with a bunch of other tasks.
