### ISSUE TITLE
Add support for a message of the day

### ISSUE THREAD

**Issue by EMERALD0874** [SteamDeckHomebrew/decky-plugin-store#36]
Create a way to get a message of the day to display at the top of the plugin store. This should have the following variables at minimum:

- Icon (GitHub, Discord, exclamation mark, question mark, and any other possible necessary icons)
- Message
- Message and icon color
- Size (Big or small display depending on intensity)
- Background color

**Comment by TrainDoctor** [comment]
Good idea @EMERALD0874 from a year ago! Sorry it took until now to implement it...
(Closing in favor of #672).
