### ISSUE TITLE
Add sort by "recently added" so it's easier for users to find newly created plugins

### ISSUE THREAD

**Issue by ttang4299** [SteamDeckHomebrew/decky-plugin-store#41]
Title

**Comment by TrainDoctor** [comment]
This is already being worked on.

**Comment by ttang4299** [comment]
Requesting this issue to be reopened as the feature has not yet been applied + I was told in the Discord anyways to open an issue in the GitHub when I first mentioned this suggestion @TrainDoctor

**Comment by TrainDoctor** [comment]
@ttang4299 sorry about that, I was clearing out issues the team has not assigned/expressed an interest in. I'm re-opening this but considering it as "under consideration".

**Comment by ttang4299** [comment]
@TrainDoctor Yes, please do consider it. There's close to 40 plugins in the repo right now. I check every day for for new plugins, and usually I can tell when a new plugin has been added if the number changes, but I can have difficulty determining which of the plugins was recently added when I'm scrolling through the entire list.

**Comment by PartyWumpus** [comment]
As of #51 The store finally has support for sorting by upload date. Decky will get support for this in the near future.
