### ISSUE TITLE
beta.deckbrew.xyz just doesn't work but is still the default for the plugin installer

### ISSUE THREAD

**Issue by PartyWumpus** [SteamDeckHomebrew/decky-plugin-store#5]
https://plugins.deckbrew.xyz/ works fine
![image](https://user-images.githubusercontent.com/48649272/176227235-499ac2bb-037f-47c8-aad7-c66acc57e54e.png)

but https://beta.deckbrew.xyz/ is completely empty
![image](https://user-images.githubusercontent.com/48649272/176227382-add6271f-acac-433d-bee0-61f804567d65.png)

this would be unhelpful but avoidable, however the Plugin Installer uses beta.deckbrew as it's default (with seemingly no way of changing it) so the browser is currently completely unusable

sorry if this is the wrong application to report the error on, but it seems to be an issue with the website, not the plugin loader

**Comment by PartyWumpus** [comment]
note that this issue occurs on:
my steam deck
firefox and google chrome on my PC
chrome on my phone, both on my wifi and on data

**Comment by Patient6038** [comment]
It's also occurring for me as well. It's a pain to install plugins since the beta site isnt even working. Im on the steam deck and it's exactly the same as vrman with me.

**Comment by marios8543** [comment]
Latest hotfix fixes this. 

> this would be unhelpful but avoidable, however the Plugin Installer uses beta.deckbrew as it's default (with seemingly no way of changing it) so the browser is currently completely unusable

For the record you can change it by setting the STORE_URL environment variable
