### ISSUE TITLE
Store Backend - Single field to force upload

### ISSUE THREAD

**Issue by TrainDoctor** [SteamDeckHomebrew/decky-plugin-store#7]
This is needed to forcefully update bad artifacts in the case of a improperly packaged build.
Single field in the form to pass a 'true' to when building the plugins (to forcibly update them). 
Example: Say you pass "force:true" in the workflow, it would update and upload the plugins to the store no matter what. 
Now, "force:false" would be passed on a normal plugin-addition (aka by default).
This is to upload newly built plugins to override their current artifacts with properly packaged versions etc.

**Comment by adntaha** [comment]
This is implemented in #9.
